Search.appendIndex(
    [
                {
            "fqsen": "\\Mursalov\\Routing\\Exceptions\\RouterException",
            "name": "RouterException",
            "summary": "",
            "url": "classes/Mursalov-Routing-Exceptions-RouterException.html"
        },                {
            "fqsen": "\\Mursalov\\Routing\\Router",
            "name": "Router",
            "summary": "Class\u0020for\u0020routing.",
            "url": "classes/Mursalov-Routing-Router.html"
        },                {
            "fqsen": "\\Mursalov\\Routing\\Router\u003A\u003AaddRoute\u0028\u0029",
            "name": "addRoute",
            "summary": "Add\u0020rout\u0020to\u0020route\u0020array.",
            "url": "classes/Mursalov-Routing-Router.html#method_addRoute"
        },                {
            "fqsen": "\\Mursalov\\Routing\\Router\u003A\u003Aroute\u0028\u0029",
            "name": "route",
            "summary": "Return\u0020callback\u0020with\u0020function\u0020which\u0020added\u0020to\u0020route.",
            "url": "classes/Mursalov-Routing-Router.html#method_route"
        },                {
            "fqsen": "\\Mursalov\\Routing\\Router\u003A\u003AcellClassMethod\u0028\u0029",
            "name": "cellClassMethod",
            "summary": "Cell\u0020method\u0020with\u0020parameters\u0020if\u0020params\u0020exist\u0020and\u0020requested\u0020in\u0020GET\u0020array.",
            "url": "classes/Mursalov-Routing-Router.html#method_cellClassMethod"
        },                {
            "fqsen": "\\Mursalov\\Routing\\Router\u003A\u003AvalidateClassAndMethod\u0028\u0029",
            "name": "validateClassAndMethod",
            "summary": "Validate\u0020class\u0020exist\u0020and\u0020method\u0020in\u0020this\u0020class\u0020exist.",
            "url": "classes/Mursalov-Routing-Router.html#method_validateClassAndMethod"
        },                {
            "fqsen": "\\Mursalov\\Routing\\Router\u003A\u003A\u0024routes",
            "name": "routes",
            "summary": "Routes\u0020array.",
            "url": "classes/Mursalov-Routing-Router.html#property_routes"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Mursalov\\Routing\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/mursalov-routing-exceptions.html"
        },                {
            "fqsen": "\\Mursalov\\Routing",
            "name": "Routing",
            "summary": "",
            "url": "namespaces/mursalov-routing.html"
        },                {
            "fqsen": "\\Mursalov",
            "name": "Mursalov",
            "summary": "",
            "url": "namespaces/mursalov.html"
        }            ]
);
